List diamondsList = [
  {
    "lot_id": "790185947",
    "size": "0.90-0.99",
    "carat": 0.9,
    "lab": "GIA",
    "shape": "BR",
    "color": "E",
    "clarity": "VVS2",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -44,
    "per_carat_rate": 3864.0,
    "final_amount": 3477.6,
    "key_to_symbol": "Cloud, Indented Natural, Cavity, Natural",
    "lab_comment": "Pinpoints are not shown."
  },
  {
    "lot_id": "490361405",
    "size": "0.90-0.99",
    "carat": 0.9,
    "lab": "GIA",
    "shape": "BR",
    "color": "G",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -41,
    "per_carat_rate": 3776.0,
    "final_amount": 3398.4,
    "key_to_symbol": "Pinpoint",
    "lab_comment": ""
  },
  {
    "lot_id": "790367521",
    "size": "1.00-1.49",
    "carat": 1.0,
    "lab": "GIA",
    "shape": "BR",
    "color": "F",
    "clarity": "VVS2",
    "cut": "VG",
    "polish": "EX",
    "symmetry": "G",
    "fluorescence": "MED",
    "discount": -58.98,
    "per_carat_rate": 3445.68,
    "final_amount": 3445.68,
    "key_to_symbol": "Cloud, Pinpoint, Indented Natural",
    "lab_comment": "Additional pinpoints are not shown. Surface graining is not shown."
  },
  {
    "lot_id": "490361912",
    "size": "1.00-1.49",
    "carat": 1.0,
    "lab": "GIA",
    "shape": "BR",
    "color": "H",
    "clarity": "VVS2",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -41,
    "per_carat_rate": 3245.0,
    "final_amount": 3245.0,
    "key_to_symbol": "Needle, Pinpoint, Indented Natural, Natural",
    "lab_comment": "Additional pinpoints are not shown."
  },
  {
    "lot_id": "790386188",
    "size": "1.00-1.49",
    "carat": 1.01,
    "lab": "GIA",
    "shape": "BR",
    "color": "F",
    "clarity": "VS1",
    "cut": "VG",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "NON",
    "discount": -49.12,
    "per_carat_rate": 3663.36,
    "final_amount": 3699.99,
    "key_to_symbol": "Crystal, Needle",
    "lab_comment": "Pinpoints are not shown. Clouds are not shown."
  },
  {
    "lot_id": "21287670",
    "size": "1.00-1.49",
    "carat": 1.01,
    "lab": "In-House",
    "shape": "BR",
    "color": "G",
    "clarity": "I1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -48.42,
    "per_carat_rate": 1598.98,
    "final_amount": 1614.97,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "790146218",
    "size": "1.00-1.49",
    "carat": 1.2,
    "lab": "GIA",
    "shape": "BR",
    "color": "G",
    "clarity": "VS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -41.48,
    "per_carat_rate": 3628.24,
    "final_amount": 4353.89,
    "key_to_symbol": "Crystal, Cloud, Needle",
    "lab_comment": "Additional clouds are not shown. Pinpoints are not shown."
  },
  {
    "lot_id": "900066231",
    "size": "1.00-1.49",
    "carat": 1.44,
    "lab": "In-House",
    "shape": "BR",
    "color": "F",
    "clarity": "VS2",
    "cut": "G",
    "polish": "G",
    "symmetry": "G",
    "fluorescence": "MED",
    "discount": -94,
    "per_carat_rate": 402.0,
    "final_amount": 578.88,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900061985",
    "size": "1.00-1.49",
    "carat": 1.46,
    "lab": "In-House",
    "shape": "BR",
    "color": "H",
    "clarity": "VS2",
    "cut": "G",
    "polish": "G",
    "symmetry": "G",
    "fluorescence": "MED",
    "discount": -94,
    "per_carat_rate": 324.0,
    "final_amount": 473.04,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "490345395",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "FL",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -18,
    "per_carat_rate": 2296.0,
    "final_amount": 688.8,
    "key_to_symbol": "",
    "lab_comment": ""
  },

  {
    "lot_id": "490370762",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -35,
    "per_carat_rate": 1560.0,
    "final_amount": 468.0,
    "key_to_symbol": "Pinpoint",
    "lab_comment": ""
  },
  {
    "lot_id": "1712094",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "VG",
    "polish": "VG",
    "symmetry": "EX",
    "fluorescence": "MED",
    "discount": -52.5,
    "per_carat_rate": 1140.0,
    "final_amount": 342.0,
    "key_to_symbol": "Cavity, Feather, Indented Natural",
    "lab_comment": ""
  },
  {
    "lot_id": "900057394",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -38,
    "per_carat_rate": 1488.0,
    "final_amount": 446.4,
    "key_to_symbol": "Pinpoint, Feather",
    "lab_comment": ""
  },
  {
    "lot_id": "900055819",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -38,
    "per_carat_rate": 1488.0,
    "final_amount": 446.4,
    "key_to_symbol": "Pinpoint",
    "lab_comment": ""
  },
  {
    "lot_id": "1706382",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "VG",
    "polish": "VG",
    "symmetry": "VG",
    "fluorescence": "FNT",
    "discount": -48,
    "per_carat_rate": 1248.0,
    "final_amount": 374.4,
    "key_to_symbol": "Pinpoint, Feather, Chip",
    "lab_comment": ""
  },
  {
    "lot_id": "290135752",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "VG",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "FNT",
    "discount": -48.5,
    "per_carat_rate": 1236.0,
    "final_amount": 370.8,
    "key_to_symbol": "Pinpoint, Feather",
    "lab_comment": ""
  },
  {
    "lot_id": "490250218",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "VG",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "FNT",
    "discount": -47.5,
    "per_carat_rate": 1260.0,
    "final_amount": 378.0,
    "key_to_symbol": "Pinpoint, Feather",
    "lab_comment": ""
  },
  {
    "lot_id": "490167040",
    "size": "0.30-0.39",
    "carat": 0.3,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "VG",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "FNT",
    "discount": -47.5,
    "per_carat_rate": 1260.0,
    "final_amount": 378.0,
    "key_to_symbol": "Pinpoint, Feather",
    "lab_comment": ""
  },
  {
    "lot_id": "900066356",
    "size": "0.18-0.22",
    "carat": 0.18,
    "lab": "In-House",
    "shape": "BR",
    "color": "D",
    "clarity": "VS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -37.67,
    "per_carat_rate": 785.36,
    "final_amount": 141.36,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900064899",
    "size": "0.18-0.22",
    "carat": 0.18,
    "lab": "In-House",
    "shape": "BR",
    "color": "D",
    "clarity": "VS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -37.67,
    "per_carat_rate": 785.36,
    "final_amount": 141.36,
    "key_to_symbol": "",
    "lab_comment": ""
  },

  {
    "lot_id": "900067131",
    "size": "0.23-0.29",
    "carat": 0.23,
    "lab": "In-House",
    "shape": "BR",
    "color": "D",
    "clarity": "SI2",
    "cut": "VG",
    "polish": "VG",
    "symmetry": "VG",
    "fluorescence": "MED",
    "discount": -37.28,
    "per_carat_rate": 683.65,
    "final_amount": 157.24,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900066716",
    "size": "0.23-0.29",
    "carat": 0.23,
    "lab": "In-House",
    "shape": "BR",
    "color": "E",
    "clarity": "SI2",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -37.28,
    "per_carat_rate": 683.65,
    "final_amount": 157.24,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900062564",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "IF",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -41,
    "per_carat_rate": 32450.0,
    "final_amount": 97674.5,
    "key_to_symbol": "",
    "lab_comment": "Minor details of polish are not shown."
  },
  {
    "lot_id": "900065188",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -39,
    "per_carat_rate": 28060.0,
    "final_amount": 84460.6,
    "key_to_symbol": "Pinpoint",
    "lab_comment": "Additional pinpoints are not shown."
  },
  {
    "lot_id": "290187276",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -43,
    "per_carat_rate": 26220.0,
    "final_amount": 78922.2,
    "key_to_symbol": "Pinpoint, Needle",
    "lab_comment": ""
  },
  {
    "lot_id": "900061478",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "BR",
    "color": "D",
    "clarity": "VVS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -38,
    "per_carat_rate": 28520.0,
    "final_amount": 85845.2,
    "key_to_symbol": "Feather",
    "lab_comment": ""
  },
  {
    "lot_id": "21214039",
    "size": "2.00-2.99",
    "carat": 2.0,
    "lab": "GIA",
    "shape": "BR",
    "color": "H",
    "clarity": "VS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -38,
    "per_carat_rate": 7750.0,
    "final_amount": 15500.0,
    "key_to_symbol": "Cloud, Crystal, Feather, Needle, Natural",
    "lab_comment": "Additional clouds are not shown. Pinpoints are not shown."
  },
  {
    "lot_id": "21269689",
    "size": "2.00-2.99",
    "carat": 2.0,
    "lab": "GIA",
    "shape": "BR",
    "color": "H",
    "clarity": "VS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -34,
    "per_carat_rate": 8250.0,
    "final_amount": 16500.0,
    "key_to_symbol": "Crystal, Cloud, Indented Natural, Natural",
    "lab_comment": "Additional clouds, pinpoints and surface graining are not shown."
  },
  {
    "lot_id": "112209404",
    "size": "2.00-2.99",
    "carat": 2.0,
    "lab": "GIA",
    "shape": "BR",
    "color": "H",
    "clarity": "VS1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -39,
    "per_carat_rate": 7625.0,
    "final_amount": 15250.0,
    "key_to_symbol": "Crystal, Indented Natural, Needle, Natural",
    "lab_comment": "Clouds, pinpoints and surface graining are not shown."
  },
  {
    "lot_id": "900064418",
    "size": "2.00-2.99",
    "carat": 2.01,
    "lab": "GIA",
    "shape": "BR",
    "color": "F",
    "clarity": "SI1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "MED",
    "discount": -51,
    "per_carat_rate": 6027.0,
    "final_amount": 12114.27,
    "key_to_symbol": "Crystal, Twinning Wisp, Feather, Needle, Indented Natural",
    "lab_comment": "Additional twinning wisps, pinpoints and surface graining are not shown."
  },
  {
    "lot_id": "1709323",
    "size": "2.00-2.99",
    "carat": 2.54,
    "lab": "HRD",
    "shape": "BR",
    "color": "F",
    "clarity": "SI2",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -48,
    "per_carat_rate": 5096.0,
    "final_amount": 12943.84,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "21126224",
    "size": "3.00-3.99",
    "carat": 3.02,
    "lab": "In-House",
    "shape": "BR",
    "color": "H",
    "clarity": "I1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "MED",
    "discount": -56.98,
    "per_carat_rate": 3527.64,
    "final_amount": 10653.47,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "21155574",
    "size": "3.00-3.99",
    "carat": 3.05,
    "lab": "In-House",
    "shape": "BR",
    "color": "H",
    "clarity": "I1",
    "cut": "EX",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -56.98,
    "per_carat_rate": 3527.64,
    "final_amount": 10759.3,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "911036108",
    "size": "2.00-2.99",
    "carat": 2.0,
    "lab": "GIA",
    "shape": "CU",
    "color": "G",
    "clarity": "VS1",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -47,
    "per_carat_rate": 7420.0,
    "final_amount": 14840.0,
    "key_to_symbol": "",
    "lab_comment": "Clouds are not shown. Pinpoints are not shown."
  },
  {
    "lot_id": "290053887",
    "size": "2.00-2.99",
    "carat": 2.01,
    "lab": "GIA",
    "shape": "CU",
    "color": "E",
    "clarity": "VVS1",
    "cut": "",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "NON",
    "discount": -52.86,
    "per_carat_rate": 8720.9,
    "final_amount": 17529.01,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900691763",
    "size": "2.00-2.99",
    "carat": 2.01,
    "lab": "GIA",
    "shape": "CU",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -60.59,
    "per_carat_rate": 5123.3,
    "final_amount": 10297.83,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900691769",
    "size": "3.00-3.99",
    "carat": 3.0,
    "lab": "GIA",
    "shape": "CU",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -56,
    "per_carat_rate": 9020.0,
    "final_amount": 27060.0,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "911036111",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "CU",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -40,
    "per_carat_rate": 12300.0,
    "final_amount": 37023.0,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "290035976",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "CU",
    "color": "H",
    "clarity": "VS1",
    "cut": "",
    "polish": "VG",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -58,
    "per_carat_rate": 8190.0,
    "final_amount": 24651.9,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "911036101",
    "size": "2.00-2.99",
    "carat": 2.01,
    "lab": "GIA",
    "shape": "EM",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -52,
    "per_carat_rate": 12542.4,
    "final_amount": 25210.22,
    "key_to_symbol": "",
    "lab_comment": "Additional clouds are not shown. Pinpoints are not shown."
  },
  {
    "lot_id": "20289242",
    "size": "2.00-2.99",
    "carat": 2.07,
    "lab": "GIA",
    "shape": "EM",
    "color": "D",
    "clarity": "VVS1",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -55.05,
    "per_carat_rate": 8990.0,
    "final_amount": 18609.3,
    "key_to_symbol": "",
    "lab_comment": "Internal graining is not shown. Surface graining is not shown."
  },
  {
    "lot_id": "290114652",
    "size": "2.00-2.99",
    "carat": 2.82,
    "lab": "GIA",
    "shape": "EM",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "NON",
    "discount": -35,
    "per_carat_rate": 8450.0,
    "final_amount": 23829.0,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "911026173",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "EM",
    "color": "F",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "VST",
    "discount": -65,
    "per_carat_rate": 7875.0,
    "final_amount": 23703.75,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "911035850",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "EM",
    "color": "F",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "NON",
    "discount": -45,
    "per_carat_rate": 12375.0,
    "final_amount": 37248.75,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "290157034",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "EM",
    "color": "F",
    "clarity": "SI1",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -46,
    "per_carat_rate": 10530.0,
    "final_amount": 31695.3,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "911024106",
    "size": "3.00-3.99",
    "carat": 3.02,
    "lab": "GIA",
    "shape": "EM",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "NON",
    "discount": -50,
    "per_carat_rate": 10250.0,
    "final_amount": 30955.0,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "7513951",
    "size": "2.00-2.99",
    "carat": 2.01,
    "lab": "GIA",
    "shape": "MQ",
    "color": "D",
    "clarity": "VVS2",
    "cut": "",
    "polish": "EX",
    "symmetry": "VG",
    "fluorescence": "NON",
    "discount": -35.41,
    "per_carat_rate": 11949.15,
    "final_amount": 24017.79,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900045732",
    "size": "2.00-2.99",
    "carat": 2.01,
    "lab": "GIA",
    "shape": "OV",
    "color": "G",
    "clarity": "VS2",
    "cut": "",
    "polish": "VG",
    "symmetry": "VG",
    "fluorescence": "NON",
    "discount": -41,
    "per_carat_rate": 7670.0,
    "final_amount": 15416.7,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900779752",
    "size": "2.00-2.99",
    "carat": 2.68,
    "lab": "GIA",
    "shape": "OV",
    "color": "E",
    "clarity": "VS1",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -32,
    "per_carat_rate": 10880.0,
    "final_amount": 29158.4,
    "key_to_symbol": "",
    "lab_comment": ""
  },
  {
    "lot_id": "900579422",
    "size": "3.00-3.99",
    "carat": 3.01,
    "lab": "GIA",
    "shape": "OV",
    "color": "G",
    "clarity": "SI1",
    "cut": "",
    "polish": "EX",
    "symmetry": "EX",
    "fluorescence": "FNT",
    "discount": -40,
    "per_carat_rate": 10800.0,
    "final_amount": 32508.0,
    "key_to_symbol": "",
    "lab_comment": ""
  }
];